// This file is automatically generated. Do not modify it manually.
import { initializeApp, getApp, getApps } from 'firebase/app';

const firebaseConfig = {"projectId":"stoicaf","appId":"1:1009179979495:web:837a6ca3377b69116e4537","storageBucket":"stoicaf.appspot.com","apiKey":"your-api-key","authDomain":"stoicaf.firebaseapp.com","messagingSenderId":"1009179979495"};

// Initialize Firebase
let app;
if (!getApps().length) {
  app = initializeApp(firebaseConfig);
} else {
  app = getApp();
}

export const firebaseApp = app;
